/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Vinylstack.glb 
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Vinylstack = React.memo(function Vinylstack(props) {
  const { nodes, materials } = useGLTF("/models/vinylstack-transformed.glb");

  const modelRef = useRef();
  const vinylStackRef = useRef(); // Separate ref for the vinyl record

  // // Bobbing effect ≈ççç
  // useFrame((state) => {
  //   modelRef.current.position.y = -1.5 + Math.sin(state.clock.elapsedTime) * 0.15; // Bobbing effect
  //   // Rotate the vinyl record continuously around its Y axis
  //   if (vinylStackRef.current) {
  //     vinylStackRef.current.rotation.y -= 0.01; // Adjust this value to control the speed of rotation
  //   }
  // });

return (
    <group {...props} dispose={null} rotation= {[0.9, -0.2, 0]}scale={[2.5,2.5,3]}>
      <group position={[-0.12, 0.726, 0.016]} rotation={[0, 0, -0.351]}>
        <mesh geometry={nodes.Cube1761.geometry} material={materials['31_A']} />
        <mesh geometry={nodes.Cube1761_1.geometry} material={materials['31_B']} />
      </group>
      <group position={[0.173, 0.74, 0.008]}>
        <mesh geometry={nodes.Cube1762.geometry} material={materials['17_A']} />
        <mesh geometry={nodes.Cube1762_1.geometry} material={materials['17_B']} />
      </group>
      <group position={[0.171, 0.74, 0.009]}>
        <mesh geometry={nodes.Cube1763.geometry} material={materials['16_A']} />
        <mesh geometry={nodes.Cube1763_1.geometry} material={materials['16_B']} />
      </group>
      <group position={[0.168, 0.74, 0.008]}>
        <mesh geometry={nodes.Cube1764.geometry} material={materials['15_A']} />
        <mesh geometry={nodes.Cube1764_1.geometry} material={materials['15_B']} />
      </group>
      <group position={[0.166, 0.74, 0.026]}>
        <mesh geometry={nodes.Cube1765.geometry} material={materials['14_A']} />
        <mesh geometry={nodes.Cube1765_1.geometry} material={materials['14_B']} />
      </group>
      <group position={[0.163, 0.74, 0.005]}>
        <mesh geometry={nodes.Cube1766.geometry} material={materials['13_A']} />
        <mesh geometry={nodes.Cube1766_1.geometry} material={materials['13_B']} />
      </group>
      <group position={[0.161, 0.735, 0.015]}>
        <mesh geometry={nodes.Cube1767.geometry} material={materials['12_A']} />
        <mesh geometry={nodes.Cube1767_1.geometry} material={materials['12_B']} />
      </group>
      <group position={[0.158, 0.74, 0.007]}>
        <mesh geometry={nodes.Cube1768.geometry} material={materials['11_A']} />
        <mesh geometry={nodes.Cube1768_1.geometry} material={materials['11_B']} />
      </group>
      <group position={[0.155, 0.74, 0.009]}>
        <mesh geometry={nodes.Cube1769.geometry} material={materials['10_A']} />
        <mesh geometry={nodes.Cube1769_1.geometry} material={materials['10_B']} />
      </group>
      <group position={[0.153, 0.735, 0.01]}>
        <mesh geometry={nodes.Cube1770.geometry} material={materials['09_A']} />
        <mesh geometry={nodes.Cube1770_1.geometry} material={materials['09_B']} />
      </group>
      <group position={[0.15, 0.74, 0.009]}>
        <mesh geometry={nodes.Cube1772.geometry} material={materials['08_A']} />
        <mesh geometry={nodes.Cube1772_1.geometry} material={materials['08_B']} />
      </group>
      <group position={[0.072, 0.74, 0.007]}>
        <mesh geometry={nodes.Cube1774.geometry} material={materials['02_A']} />
        <mesh geometry={nodes.Cube1774_1.geometry} material={materials['02_B']} />
      </group>
      <group position={[0.07, 0.74, 0.006]}>
        <mesh geometry={nodes.Cube1775.geometry} material={materials['35_A']} />
        <mesh geometry={nodes.Cube1775_1.geometry} material={materials['35_B']} />
      </group>
      <group position={[0.067, 0.74, 0.008]}>
        <mesh geometry={nodes.Cube1776.geometry} material={materials['33_A']} />
        <mesh geometry={nodes.Cube1776_1.geometry} material={materials['33_B']} />
      </group>
      <group position={[0.062, 0.74, 0.005]}>
        <mesh geometry={nodes.Cube1778.geometry} material={materials['29_A']} />
        <mesh geometry={nodes.Cube1778_1.geometry} material={materials['29_B']} />
      </group>
      <group position={[0.06, 0.735, 0.015]}>
        <mesh geometry={nodes.Cube1779.geometry} material={materials['27_A']} />
        <mesh geometry={nodes.Cube1779_1.geometry} material={materials['27_B']} />
      </group>
      <group position={[0.057, 0.74, 0.007]}>
        <mesh geometry={nodes.Cube1780.geometry} material={materials['25_A']} />
        <mesh geometry={nodes.Cube1780_1.geometry} material={materials['25_B']} />
      </group>
      <group position={[0.055, 0.74, 0.009]}>
        <mesh geometry={nodes.Cube1781.geometry} material={materials['23_A']} />
        <mesh geometry={nodes.Cube1781_1.geometry} material={materials['23_B']} />
      </group>
      <group position={[0.052, 0.735, 0.01]}>
        <mesh geometry={nodes.Cube1782.geometry} material={materials['21_A']} />
        <mesh geometry={nodes.Cube1782_1.geometry} material={materials['21_B']} />
      </group>
      <group position={[0.143, 0.735, 0.024]}>
        <mesh geometry={nodes.Cube1783.geometry} material={materials['05_A']} />
        <mesh geometry={nodes.Cube1783_1.geometry} material={materials['05_B']} />
      </group>
      <group position={[0.138, 0.74, 0.002]}>
        <mesh geometry={nodes.Cube1784.geometry} material={materials['03_A']} />
        <mesh geometry={nodes.Cube1784_1.geometry} material={materials['03_B']} />
      </group>
      <group position={[0.133, 0.74, 0.005]}>
        <mesh geometry={nodes.Cube1786.geometry} material={materials['01_A']} />
        <mesh geometry={nodes.Cube1786_1.geometry} material={materials['01_B']} />
      </group>
      <group position={[0.128, 0.74, 0.009]}>
        <mesh geometry={nodes.Cube1788.geometry} material={materials['30_A']} />
        <mesh geometry={nodes.Cube1788_1.geometry} material={materials['30_B']} />
      </group>
      <group position={[0.123, 0.74, 0.008]}>
        <mesh geometry={nodes.Cube1790.geometry} material={materials['20_A']} />
        <mesh geometry={nodes.Cube1790_1.geometry} material={materials['20_B']} />
      </group>
      <group position={[0.113, 0.74, 0.009]}>
        <mesh geometry={nodes.Cube1794.geometry} material={materials['34_A']} />
        <mesh geometry={nodes.Cube1794_1.geometry} material={materials['34_B']} />
      </group>
      <group position={[0.14, 0.74, 0.006]}>
        <mesh geometry={nodes.Cube1795.geometry} material={materials['04_A']} />
        <mesh geometry={nodes.Cube1795_1.geometry} material={materials['04_B']} />
      </group>
      <group position={[0.145, 0.74, 0.005]}>
        <mesh geometry={nodes.Cube1796.geometry} material={materials['06_A']} />
        <mesh geometry={nodes.Cube1796_1.geometry} material={materials['06_B']} />
      </group>
      <group position={[0.148, 0.735, 0.016]}>
        <mesh geometry={nodes.Cube1797.geometry} material={materials['07_A']} />
        <mesh geometry={nodes.Cube1797_1.geometry} material={materials['07_B']} />
      </group>
      <group position={[0.1, 0.735, 0.015]}>
        <mesh geometry={nodes.Cube1798.geometry} material={materials['24_A']} />
        <mesh geometry={nodes.Cube1798_1.geometry} material={materials['24_B']} />
      </group>
      <group position={[0.098, 0.74, 0.007]}>
        <mesh geometry={nodes.Cube1799.geometry} material={materials['22_A']} />
        <mesh geometry={nodes.Cube1799_1.geometry} material={materials['22_B']} />
      </group>
      <group position={[0.11, 0.74, 0.007]}>
        <mesh geometry={nodes.Cube1800.geometry} material={materials['32_A']} />
        <mesh geometry={nodes.Cube1800_1.geometry} material={materials['32_B']} />
      </group>
      <group position={[0.093, 0.735, 0.01]}>
        <mesh geometry={nodes.Cube1802.geometry} material={materials['18_A']} />
        <mesh geometry={nodes.Cube1802_1.geometry} material={materials['18_B']} />
      </group>
      <group position={[0.103, 0.74, 0.006]}>
        <mesh geometry={nodes.Cube1809.geometry} material={materials['26_A']} />
        <mesh geometry={nodes.Cube1809_1.geometry} material={materials['26_B']} />
      </group>
      <group position={[0.105, 0.74, 0.016]}>
        <mesh geometry={nodes.Cube1810.geometry} material={materials['28_A']} />
        <mesh geometry={nodes.Cube1810_1.geometry} material={materials['28_B']} />
      </group>
      <group position={[0.05, 0.74, 0.009]}>
        <mesh geometry={nodes.Cube1812.geometry} material={materials['19_A']} />
        <mesh geometry={nodes.Cube1812_1.geometry} material={materials['19_B']} />
      </group>
    </group>
  );
});

export default Vinylstack;
useGLTF.preload("/models/vinylstack-transformed.glb");
